### ISSUE TITLE
Time Quantization unavailable for imported audio in Logic Pro

### ISSUE THREAD

**Issue by natewiedemann** [DamRsn/NeuralNote#106]
When using the load/drop option for audio import, Time Quantize is not available (greyed out). However, Time Quantize does work when recording audio into the plugin by playing it in the DAW and enabling record in the plugin. Is this normal behavior? It would be nice to have Time Quantize available for offline processing / to avoid taking time to record in the audio.

**Comment by DamRsn** [comment]
Hi,

Time quantize is currently not available when importing audio because there's no tempo and timing information available. 

For the time quantize to work when recording, the DAW should already be playing when record is clicked. It won't work if you first click record and then play in the DAW unfortunately.

In a future update, I want to have the following behavior:
- Recording:
   - Time quantize always available.
- Audio import:
   - Let the user specify the tempo and time signature
   - Assume the start of the Sample is the start of a measure.
