### ISSUE TITLE
daw doesnt recognise parameters

### ISSUE THREAD

**Issue by RustoMCSpit** [DamRsn/NeuralNote#45]

**Comment by DamRsn** [comment]
Yes the parameters handling is pretty messy at the moment. I plan on refactoring it in the future. 

At least I'd like to have the plugin state save and restore properly when closing and reopening a DAW session for example. 

But I don't know if all the parameters should be recognized by the DAW, because I don't want the Transcription options to be automatable for example, it would not make sense.

**Comment by RustoMCSpit** [comment]
> Transcription options to be automatable

rule of thumb, let everything be automatable. i can imagine it being useful for comping if there was also automatable saving and exporting

**Comment by DamRsn** [comment]
Fixed with #102
