### ISSUE TITLE
please help how to enable time quantize

### ISSUE THREAD

**Issue by novanandriyono** [DamRsn/NeuralNote#82]
![image](https://github.com/DamRsn/NeuralNote/assets/7598624/18a21c46-c54a-4893-8355-d89d5ebec105)

**Comment by DamRsn** [comment]
Hi!

Currently, time quantization is only enabled if:
- The source audio was **recorded** (in opposition to **loaded** from a file)
- The DAW playhead was moving at the moment you clicked the record button

This is due to how the tempo and grid information is gathered by NeuralNote from the DAW.

Hope this helps.

One thing I could implement is letting the user choose whether to time quantize when a file is dropped. The user would have to manually enter the tempo and time signature, and NeuralNote would assume that a measure starts at `t = 0s`.

**Comment by DamRsn** [comment]
I see that you're using the standalone version. Currently the time quantize does not work with the Standalone version as we can't get grid information from DAW (as there's no DAW).

**Comment by novanandriyono** [comment]
and  also info for you disabled on vst plugin 
its ok thanks for your help @DamRsn ..
