### ISSUE TITLE
Adjusting dials on NeuralNote Standalone is awkward

### ISSUE THREAD

**Issue by mslinn** [DamRsn/NeuralNote#99]
There is no way to type in numeric values or use the up and down arrows to adjust the values; instead, the little knobs must be turned, which is awkward with this UI.

**Comment by DamRsn** [comment]
Hi,

What do you mean by awkward? It is pretty standard in plugins to have rotary knobs. I could add the text to value though as it's true that it is handy.

Regarding the up/down arrows, it is more complicated as you'd need to keep track of what was selected last. So I don't think to include it.

One thing to know in order to use knobs easily in NeuralNote is that they should be dragged vertically to change their value. Trying to rotate them with the mouse will not work properly.

Hope this helps!
